---
- name: Check cinder containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes | reject('equalto', '') | list }}"
    dimensions: "{{ item.value.dimensions }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    ipc_mode: "{{ item.value.ipc_mode | default('') }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
    - item.key != 'cinder-volume' or pacemaker_manage_cinder_volume is not defined or not pacemaker_manage_cinder_volume | bool
  with_dict: "{{ cinder_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Waiting for cinder-volume to start
  vars:
    service_name: "cinder-volume"
    service: "{{ cinder_services[service_name] }}"
  delegate_to: "{{ groups['cinder-volume'][0] }}"
  run_once: True
  become: True
  shell: 'docker exec pacemaker crm resource locate p_{{ service_name }}'
  register: result
  until: "'resource p_' ~ service_name ~ ' is running on:' in result.stdout"
  changed_when: False
  retries: 12
  delay: 5
  when:
    - service.enabled | bool
    - pacemaker_manage_cinder_volume is defined
    - pacemaker_manage_cinder_volume | bool
  notify:
    - "Restart {{ service_name }} container with Pacemaker"
