---
- name: Check RSYSLOG containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
    dimensions: "{{ item.value.dimensions }}"
    privileged: "{{ item.value.privileged }}"
    pid_mode: "{{ item.value.pid_mode }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ rsyslog_services }}"
  notify:
    - Restart systemd syslog.socket
