---
- name: Copying over logrotate main config file
  template:
    src: "logrotate.conf.j2"
    dest: "{{ logrotate_main_config_file_path }}"
    mode: "{{ logrotate_config_file_mode }}"
  become: true
  when:
    - enable_rsyslog | bool

- name: Make sure logrotate include directory exists
  file:
    path: "{{ logrotate_config_include_directory_path }}"
    state: "directory"
    mode: "{{ logrotate_config_include_directory_mode }}"
  become: true
  when:
    - enable_rsyslog | bool
