- name: Create btrfs subvolumes
  command: "btrfs subvolume create {{ installroot }}{{ subvol.name }}"
  loop: "{{ volume.subvolumes }}"
  loop_control:
    loop_var: subvol
  when:
  - "'subvolumes' in volume"

# The mount module can update the fstab for the subvolumes but it cannot mount them
- name: Mount btrfs subvolumes in {{ installroot }}
  command:
    cmd: "mount {{volume.device}} -o subvol={{ subvol.name | regex_replace('^\\/', '') }} {{ installroot }}{{ subvol.name }}"
    warn: false
  loop: "{{ volume.subvolumes }}"
  loop_control:
    loop_var: subvol
  when:
  - "'subvolumes' in volume"
