---
#TODO: add endpoint if need
#- include_tasks: register.yml
#  when: inventory_hostname in groups['notifier-controller']

- include_tasks: config.yml
  when: inventory_hostname in groups['notifier-controller'] or
        inventory_hostname in groups['notifier-requeuer'] or
        inventory_hostname in groups['notifier-emitter']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['notifier-controller']

#TODO: Enable when firewall config is in place
#- include_tasks: firewall.yml

- name: Flush handlers
  meta: flush_handlers
