---
- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"
  notify:
    - Restart {{ item.key }} container

- name: "Getting {{ keystone_admin_project }} ID for Watchmen conf"
  kolla_toolbox:
    module_name: "os_project"
    module_args:
      name: "{{ keystone_admin_project }}"
      domain: "{{ openstack_auth.domain_name }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ watchmen_keystone_auth }}"
      interface: "{{ openstack_interface }}"
  register: get_admin_project_id_result

- name: Copying over config files for services
  become: true
  merge_configs:
    sources:
      - "{{ role_path }}/templates/{{ item.key }}.conf.j2"
      - "{{ node_custom_config }}/{{ item.key }}.conf"
      - "{{ node_custom_config }}/{{ item.key }}/{{ item.key }}.conf"
      - "{{ node_custom_config }}/{{ item.key }}/{{ inventory_hostname }}/{{ item.key }}.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.conf"
    mode: "0660"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over logging config files for services
  become: true
  template:
    src: "watchmen-service-logging.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}-logging.conf"
    mode: "0660"
  vars:
    watchmen_service_name: "{{ item.key }}"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over watchmen consumer setup config file
  become: true
  template:
    src: "watchmen-consumer-setup.conf.j2"
    dest: "{{ node_config_directory }}/watchmen-consumer/watchmen-consumer-setup.conf"
    mode: "0660"
  when:
    - watchmen_services['watchmen-consumer'].enabled | bool
    - inventory_hostname in groups[watchmen_services['watchmen-consumer'].group]
  notify:
    - Restart watchmen-consumer container

- name: Ensuring config directory exists on Watchmen hosts
  become: true
  file:
    path: "/etc/watchmen"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0750"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"

- include: config_producer.yml
  vars:
    dest_dir: "/etc/watchmen"
    dest_mode: "0640"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"

- include: config_producer.yml
  vars:
    service_name: "{{ item.key }}"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ watchmen_services }}"
  notify:
    - Restart {{ item.key }} container

- include_tasks: check-containers.yml
  when: kolla_action != "config"
