---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - watchmen_api
  register: container_facts

- name: Checking free port for Watchmen API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ watchmen_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['watchmen_api'] is not defined
    - inventory_hostname in groups['watchmen-api']
