---
- name: Gather group facts
  run_once: True
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups[project_name] }}"
  when: not (groups[project_name] is subset(ansible_play_batch))
