---
- name: Restart sa_api container
  vars:
    service_name: "sa_api"
    service: "{{ sa_api_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    labels:
      service-component: "{{ service_name }}"
  when:
    - kolla_action != "config"
