---
# NOTE deploy portal standalone:
# ansible-playbook -i /opt/cee/source/kolla-ansible/ansible/inventory/seed-portal \
#    -e portal_lcm_api_url='http://192.168.0.33' \
#    -e portal_lcm_api_port='8081' \
#    -e portal_port=8080 \
#    -e kolla_action=deploy \
#    /opt/cee/source/kolla-ansible/ansible/cee_portal.yml

- hosts:
    - localhost
    - lcm_hosts
  vars:
    node_config_directory: "/etc/kolla"
  tasks:
    - name: Include seed_vm docker vars
      include_vars: /opt/cee/source/ansible/roles/docker/vars/main.yml
    - name: Include seed_vm docker registery vars
      include_vars: /opt/cee/source/ansible/roles/docker-registry/defaults/main.yml

- hosts:
    - localhost
    - lcm_hosts
  vars:
    node_config_directory: "/etc/kolla"
    config_owner_user: "ceeinfra"
    config_owner_group: "ceeinfra"
    enable_portal: "yes"
    enable_openstack_core: "no"
    enable_glance: "no"
    enable_haproxy: "no"
    enable_keepalived: "no"
    enable_keystone: "no"
    enable_mariadb: "no"
    enable_memcached: "no"
    enable_neutron: "no"
    enable_nova: "no"
    enable_rabbitmq: "no"
    enable_elasticsearch: "no"
    enable_kibana: "no"
    enable_aodh: "no"
    enable_barbican: "no"
    enable_blazar: "no"
    enable_ceilometer: "no"
    enable_ceph: "no"
    enable_chrony: "no"
    enable_cinder: "no"
    enable_cloudkitty: "no"
    enable_collectd: "no"
    enable_congress: "no"
    enable_cyborg: "no"
    enable_designate: "no"
    enable_etcd: "no"
    enable_fluentd: "no"
    enable_freezer: "no"
    enable_gnocchi: "no"
    enable_grafana: "no"
    enable_heat: "no"
    enable_horizon: "no"
    enable_hyperv: "no"
    enable_influxdb: "no"
    enable_ironic: "no"
    enable_ironic_ipxe: "no"
    enable_ironic_neutron_agent: "no"
    enable_ironic_pxe_uefi: "no"
    enable_iscsid: "no"
    enable_karbor: "no"
    enable_kafka: "no"
    enable_kuryr: "no"
    enable_magnum: "no"
    enable_manila: "no"
    enable_mariabackup: "no"
    enable_masakari: "no"
    enable_mistral: "no"
    enable_monasca: "no"
    enable_mongodb: "no"
    enable_multipathd: "no"
    enable_murano: "no"
    enable_octavia: "no"
    enable_onos: "no"
    enable_opendaylight: "no"
    enable_openvswitch: "no"
    enable_ovsdpdk: "no"
    enable_osprofiler: "no"
    enable_pacemaker: "no"
    enable_panko: "no"
    enable_placement: "no"
    enable_prometheus: "no"
    enable_qdrouterd: "no"
    enable_qinling: "no"
    enable_rally: "no"
    enable_redis: "no"
    enable_sahara: "no"
    enable_searchlight: "no"
    enable_senlin: "no"
    enable_sa_api: "no"
    enable_skydive: "no"
    enable_solum: "no"
    enable_storm: "no"
    enable_swift: "no"
    enable_swift_s3api: "no"
    enable_swift_recon: "no"
    enable_tacker: "no"
    enable_telegraf: "no"
    enable_tempest: "no"
    enable_trove: "no"
    enable_vitrage: "no"
    enable_vmtp: "no"
    enable_watcher: "no"
    enable_watchmen: "no"
    enable_notifier: "no"
    enable_zookeeper: "no"
    enable_zun: "no"
    enable_outward_rabbitmq: "no"
    docker_registry_email:
    docker_registry_username:
    docker_runtime_directory: ""
    docker_registry_password:
    docker_namespace: "cee"
    docker_restart_policy: "unless-stopped"
    docker_restart_policy_retry: "10"
    docker_graceful_timeout: 60
    config_strategy: "COPY_ALWAYS"
    docker_common_options:
      auth_email: "{{ docker_registry_email }}"
      auth_password: "{{ docker_registry_password }}"
      auth_registry: "{{ docker_registry }}"
      auth_username: "{{ docker_registry_username }}"
      environment:
        KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      restart_policy: "{{ docker_restart_policy }}"
      restart_retries: "{{ docker_restart_policy_retry }}"
      graceful_timeout: "{{ docker_graceful_timeout }}"
    default_container_dimensions:
      cgroup_parent: container.slice
    default_extra_volumes: []
    kolla_base_distro: "sles"
    kolla_install_type: "binary"
    openstack_release: "9.0.0.2"
    container_config_directory: "/var/lib/kolla/config_files"
    portal_port: "8080"
    portal_listen_port: "{{ portal_port }}"

  roles:
    - portal
