---
- name: Check Pacemaker containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    dimensions: "{{ item.value.dimensions }}"
    environment: "{{ item.value.environment }}"
    cap_add: "{{ item.value.cap_add|default([]) }}"
    ipc_mode: "{{ item.value.ipc_mode }}"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ pacemaker_services }}"
  notify:
    - "Restart {{ item.key }} container"
