- name: Ensure glusterd service override dir
  file:
    name: /etc/systemd/system/glusterd.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create glusterd service override
  template:
    src: glusterd.service.override.j2
    dest: /etc/systemd/system/glusterd.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- mount:
    src: "{{gluster_mounts[item].server|d('localhost')}}:/{{item}}"
    path: "{{gluster_mounts[item].mountpoint}}"
    fstype: glusterfs
    state: mounted
  with_items: "{{gluster_mounts}}"
