---
- name: Restart notifier-emitter container
  vars:
    service_name: "notifier-emitter"
    service: "{{ notifier_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"

- name: Restart notifier-requeuer container
  vars:
    service_name: "notifier-requeuer"
    service: "{{ notifier_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"

# Pull notifier-controller image on each node, so it will be available
# on service failover
- name: Pull notifier-controller image
  vars:
    service_name: "notifier-controller"
    service: "{{ notifier_services[service_name] }}"
  become: true
  kolla_docker:
    action: "pull_image"
    image: "{{ service.image }}"
  when:
    - enable_pacemaker | bool
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  listen: "Restart notifier-controller container"

- name: Create Notifier-Controller resource
  vars:
    service_name: "notifier-controller"
    service: "{{ notifier_services[service_name] }}"
    volumes: >-
      {% set volumes = [] -%}
      {% for volume in service['volumes'] -%}
        {% if volume -%}
          {% if volume[0] != '/' and volume.split(':') | length == 2 -%}
            {% set elem = volume ~ ':rw' -%}
            {{ volumes.append(elem) -}}
          {% else -%}
            {{ volumes.append(volume) -}}
          {% endif -%}
        {% endif -%}
      {% endfor -%}
      {{ volumes | map('regex_replace', '(.*)', '-v \1') | join(' ') -}}
    service_dimensions: "{{ service['dimensions'] }}"
    kolla_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      KOLLA_SERVICE_NAME: "{{ service_name }}"
    service_environment: >-
      {% set service_environment = [] -%}
      {% for key, value in kolla_environment.items() -%}
        {% set elem = key ~ '=' ~ value -%}
        {{ service_environment.append(elem) -}}
      {% endfor -%}
      {{ service_environment | map('regex_replace', '(.*)', '-e \1') | join(' ') -}}
    cgroup_parent: "{{ '--cgroup-parent=' ~ service['dimensions']['cgroup_parent'] if 'cgroup_parent' in service['dimensions'] else '' }}"
    run_opts: "--net=host {{ volumes }} {{ service_environment }} {{ cgroup_parent }}"
  delegate_to: "{{ groups['pacemaker'][0] }}"
  become: True
  run_once: True
  pacemaker:
    action: add_resource
    name: "p_{{ service_name }}"
    type: primitive
    agent: 'ocf:heartbeat:docker'
    recreate: True
    parameter:
      image: "{{ service.image }}"
      name: "{{ service_name | replace('-', '_') }}"
      allow_pull: "true"
      run_opts: "{{ run_opts }}"
      run_cmd: "kolla_start"
      query_docker_health: "true"
      force_kill: "true"
      reuse: "false"
    operation:
      monitor:
        interval: "30s"
        timeout: "30s"
    meta:
      failure-timeout: 120
  when:
    - enable_pacemaker | bool
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  listen: "Restart notifier-controller container"

- name: Put notifier-controller role for its hosting node
  vars:
    service_name: "notifier-controller"
    service: "{{ notifier_services[service_name] }}"
  delegate_to: "{{ groups['pacemaker'][0] }}"
  become: True
  run_once: True
  pacemaker:
    action: set_node_attribute
    node: "{{ hostvars[item]['hostname_full'] }}"
    attribute: "{{ service_name }}-role"
    value: "true"
  loop: "{{ groups[service_name] }}"
  when:
    - enable_pacemaker | bool
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  listen: "Restart notifier-controller container"

- name: Restrict notifier-controller instance location
  vars:
    service_name: "notifier-controller"
    service: "{{ notifier_services[service_name] }}"
  delegate_to: "{{ groups['pacemaker'][0] }}"
  become: True
  run_once: True
  pacemaker:
    action: add_location_constraint
    name: "location-{{ service_name }}"
    resource: "p_{{ service_name }}"
    attribute: "resource-discovery=exclusive"
    rules: "rule 100: {{ service_name }}-role eq true"
  when:
    - enable_pacemaker | bool
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  listen: "Restart notifier-controller container"

- name: Waiting for notifier-controller to start
  vars:
    service_name: "notifier-controller"
    service: "{{ notifier_services[service_name] }}"
  delegate_to: "{{ groups['pacemaker'][0] }}"
  run_once: True
  become: True
  shell: 'docker exec pacemaker crm resource locate p_{{ service_name }}'
  register: result
  until: "'resource p_' ~ service_name ~ ' is running on:' in result.stdout"
  changed_when: False
  retries: 12
  delay: 5
  when:
    - enable_pacemaker | bool
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  listen: "Restart notifier-controller container"

- name: Restart notifier-controller container if Pacemaker is absent
  vars:
    service_name: "notifier-controller"
    service: "{{ notifier_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    labels:
      service-component: "{{ service_name }}"
  when:
    - not enable_pacemaker | bool
    - kolla_action != "config"
  listen: "Restart notifier-controller container"
