- name: Install required packages
  become: yes
  package:
    name: "{{ lcm_required_packages }}"
    state: latest
- include_tasks: apache.yml
- include_tasks: lcm-api.yml
- include_tasks: lcm-cli.yml
