---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cmha_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: cmha_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/cmha/"
      skip: true

- name: Set cmha policy file
  set_fact:
    cmha_policy_file: "{{ cmha_policy.results.0.stat.path | basename }}"
    cmha_policy_file_path: "{{ cmha_policy.results.0.stat.path }}"
  when:
    - cmha_policy.results

- name: Copying over existing policy file
  template:
    src: "{{ cmha_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ cmha_policy_file }}"
    mode: "0660"
  become: true
  when:
    - cmha_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ cmha_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cmha_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over cmha.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/cmha.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/cmha.conf"
      - "{{ node_custom_config }}/cmha/{{ item.key }}.conf"
      - "{{ node_custom_config }}/cmha/{{ inventory_hostname }}/cmha.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/cmha.conf"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cmha_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copy over watchmen configs
  vars:
    service_name: "{{ item.key }}"
  include_role:
    role: watchmen
    tasks_from: config_producer
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cmha_services }}"
  register: template_result

- name: Restart container after copying over watchmen configs
  vars:
    service_name: "{{ item.key }}"
  debug:
    msg: "restart {{ item.key }}"
  when:
    - template_result.changed
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cmha_services }}"
  notify:
    - "Restart {{ item.key }} container"

- include_tasks: check-containers.yml
  when: kolla_action != "config"
