---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - cmha
  register: container_facts

- name: Checking free port for cmha
  wait_for:
    host: "{{ cmha_interface_address }}"
    port: "{{ cmha_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['cmha'] is not defined
    - inventory_hostname in groups['cmha']
