---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_cmha_auth }}"
    service_ks_register_services: "{{ cmha_ks_services }}"
    service_ks_register_users: "{{ cmha_ks_users }}"
  tags: always
