---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sa_api_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sa_api_services }}"
  notify:
    - Restart sa_api container

- name: Copying over sac api wsgi configuration
  template:
    src: "sa_api_wsgi.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/sa_api_wsgi.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sa_api_services }}"
  notify:
    - Restart sa_api container

- name: Copying over sac api configuration
  template:
    src: "sa_api.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/sa_api.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sa_api_services }}"
  notify:
    - Restart sa_api container

- include_tasks: check-containers.yml
  when: kolla_action != "config"
