---
- include_tasks: register.yml
  when: inventory_hostname in groups['sa_api']

- include_tasks: config.yml

#TODO: Enable when firewall config is in place
#- include_tasks: firewall.yml

- name: Flush handlers
  meta: flush_handlers
