---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - sa_api
  register: container_facts

- name: Checking free port for sac api
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ sa_api_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['sa_api'] is not defined
    - inventory_hostname in groups['sa_api']
