---
project_name: "sa_api"

sa_api_services:
  sa_api:
    container_name: sa_api
    group: sa_api
    enabled: "{{ enable_sa_api | bool }}"
    image: "{{ sa_api_image_full }}"
    volumes: "{{ sa_api_default_volumes + sa_api_extra_volumes }}"
    dimensions: "{{ sa_api_dimensions }}"
    haproxy:
      sa-api:
        enabled: "{{ enable_sa_api }}"
        mode: "http"
        frontend_http_extra:
          - "balance roundrobin"
        external: false
        port: "{{ sa_api_port }}"
        listen_port: "{{ sa_api_listen_port }}"
      sa-api-external:
        enabled: "{{ enable_sa_api }}"
        mode: "http"
        frontend_http_extra:
          - "balance roundrobin"
        external: true
        port: "{{ sa_api_port }}"
        listen_port: "{{ sa_api_listen_port }}"

####################
# Sac api
####################
sa_api_logging_debug: "False"

####################
# Keystone
####################
sa_api_keystone_auth: "{{ openstack_auth }}"
sa_api_keystone_auth_url: "{{ keystone_internal_url }}/v3"
sa_api_keystone_user: "sa_api"
sa_api_keystone_role: "sa_api"

sa_api_keystone_users:
  - project: "service"
    user: "{{ sa_api_keystone_user }}"
    password: "{{ sa_api_keystone_password }}"
    role: "admin"

sa_api_keystone_roles:
  - "{{ sa_api_keystone_role }}"

####################
# Docker
####################
sa_api_install_type: "{{ kolla_install_type }}"
sa_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ sa_api_install_type }}-sa-api"
sa_api_tag: "{{ openstack_release }}"
sa_api_image_full: "{{ sa_api_image }}:{{ sa_api_tag }}"
sa_api_dimensions: "{{ default_container_dimensions }}"

sa_api_default_volumes:
  - "{{ node_config_directory }}/sa_api/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
sa_api_extra_volumes: "{{ default_extra_volumes }}"
