---
- include_tasks: gather_group_facts.yml

- include_tasks: check_pacemaker_cluster.yml

- include_tasks: check_service_cluster.yml

- import_tasks: wait_for_loadbalancer.yml

- include_tasks: check.yml
