---
- name: Restart collectd container
  vars:
    service_name: "collectd"
    service: "{{ collectd_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes | append_host_mounts(my_disk_assignments['volumes']) }}"
    dimensions: "{{ service.dimensions }}"
    labels:
      service-component: "{{ service_name }}"
  when:
    - kolla_action != "config"
