---
- name: Deleting backup for {{ backupname }}
  backup_restore:
    action: "delete"
    backupname: "{{ backupname }}"
    location: "{{ backup_path }}"
    clustername: "{{ cluster_name }}"
    backupdomain: "{{ brf_domain }}"
    backup_db_info: "{{ backup_db_info }}"
  delegate_to: localhost
  when: inventory_hostname == groups[brf_group][0]
