---
- name: Get backup info for {{ backupname }}
  backup_restore:
    action: "show"
    backupname: "{{ backupname }}"
    location: "{{ backup_temp }}"
    clustername: "{{ cluster_name }}"
    backupdomain: "{{ brf_domain }}"
    backup_db_info: "{{ backup_db_info }}"
  when: inventory_hostname == groups[brf_group][0]
  register: backup_info

- name: Display backup information for {{ backupname }}
  debug:
    msg: "{{ backup_info.output }}"
  when: inventory_hostname == groups[brf_group][0]
