---
- name: Restart corosync container
  vars:
    service_name: "corosync"
    service: "{{ pacemaker_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    environment: "{{ service.environment }}"
    cap_add: "{{ service.cap_add | default([]) }}"
    ipc_mode: "{{ service.ipc_mode }}"
    labels:
      service-component: "{{ service_name }}"
  when:
    - kolla_action != "config"

- name: Restart pacemaker container
  vars:
    service_name: "pacemaker"
    service: "{{ pacemaker_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    environment: "{{ service.environment }}"
    cap_add: "{{ service.cap_add | default([]) }}"
    ipc_mode: "{{ service.ipc_mode }}"
    labels:
      service-component: "{{ service_name }}"
  when:
    - kolla_action != "config"
